import os
import requests
from dotenv import load_dotenv

load_dotenv()

GITLAB_TOKEN = os.getenv("GITLAB_TOKEN")
GITLAB_BASE_URL = "https://gitlab.com/api/v4"


def create_gitlab_issue(gitlab_project_id, finding, before_proof: dict, after_proof: dict, attempts: int) -> str:
    """
    Creates a GitLab Issue with the full vulnerability report.
    Includes a before/after proof comparison table, educational explanation, and fix details.
    Returns the issue URL.
    """
    vulnerable_code_block = "```\n" + finding.vulnerable_code + "\n```"
    fixed_code_block = "```\n" + finding.fixed_code + "\n```"

    # Side-by-side before/after comparison — easier to read than separate sections
    proof_table = (
        "| | Before Fix | After Fix |\n"
        "|---|---|---|\n"
        f"| **Payload** | `{before_proof['payload_used']}` | `{after_proof['payload_used']}` |\n"
        f"| **Target Field** | `{before_proof['field_targeted']}` | `{after_proof['field_targeted']}` |\n"
        f"| **HTTP Status** | {before_proof['status_code']} | {after_proof['status_code']} |\n"
        f"| **Response** | {before_proof['response_body'][:50]} | {after_proof['response_body'][:50]} |\n"
        f"| **Result** | :red_circle: Attack succeeded | :green_circle: Attack blocked |\n"
    )

    issue_body = (
        "## :red_circle: Security Vulnerability Detected by SecureAgent\n\n"
        f"**Vulnerability:** {finding.vulnerability}\n"
        f"**Severity:** {finding.severity}\n"
        f"**OWASP Category:** {finding.owasp_category}\n"
        f"**File:** Line {finding.line_number}\n\n"
        "---\n\n"
        "## Vulnerable Code\n"
        f"{vulnerable_code_block}\n\n"
        "## Why This Is Vulnerable\n"
        f"{finding.why_vulnerable}\n\n"
        "## Real World Impact\n"
        f"{finding.real_world_impact}\n\n"
        "---\n\n"
        "## Live Attack Proof\n"
        f"{proof_table}\n\n"
        f"Fix verified in {attempts} attempt(s).\n\n"
        "---\n\n"
        "## Recommended Fix\n"
        f"{fixed_code_block}\n\n"
        "## Why The Fix Works\n"
        f"{finding.why_fix_works}\n\n"
        "## Developer Lesson\n"
        f"{finding.developer_lesson}\n\n"
        "---\n\n"
        "## Scope\n"
        "SecureAgent currently analyses changed Python and JavaScript files per MR push.\n"
        "Live attack proof is currently supported for SQL Injection only.\n"
        "XSS detection and fix generation is supported without sandbox verification.\n"
        "Cross-file and second-order vulnerability detection is on the roadmap (Phase 3).\n\n"
        "*This issue was automatically generated by SecureAgent.*"
    )

    url = f"{GITLAB_BASE_URL}/projects/{gitlab_project_id}/issues"
    headers = {"PRIVATE-TOKEN": GITLAB_TOKEN}
    data = {
        "title": f"[SecureAgent] {finding.severity} {finding.vulnerability} detected",
        "description": issue_body,
        "labels": "security,secureagent"
    }

    response = requests.post(url, headers=headers, json=data)

    if response.status_code == 201:
        issue_url = response.json().get("web_url")
        print(f"GitLab Issue created: {issue_url}")
        return issue_url
    else:
        print(f"Failed to create issue: {response.status_code}")
        return None


def ensure_fixes_branch(gitlab_project_id, source_branch: str) -> bool:
    """
    Ensures the secureagent/fixes branch exists in the repo.
    Creates it from the source branch HEAD if it doesn't exist yet.
    Only needs to run once per repo, subsequent calls return True immediately.
    """
    headers = {"PRIVATE-TOKEN": GITLAB_TOKEN}
    branch_name = "secureagent/fixes"

    check_url = f"{GITLAB_BASE_URL}/projects/{gitlab_project_id}/repository/branches/{branch_name.replace('/', '%2F')}"
    check_response = requests.get(check_url, headers=headers)

    if check_response.status_code == 200:
        print("secureagent/fixes branch already exists")
        return True

    # Get source branch HEAD commit SHA to branch from
    ref_url = f"{GITLAB_BASE_URL}/projects/{gitlab_project_id}/repository/branches/{source_branch}"
    ref_response = requests.get(ref_url, headers=headers)

    if ref_response.status_code != 200:
        print(f"Failed to get source branch info: {ref_response.status_code}")
        return False

    commit_sha = ref_response.json()["commit"]["id"]

    create_url = f"{GITLAB_BASE_URL}/projects/{gitlab_project_id}/repository/branches"
    create_response = requests.post(create_url, headers=headers, json={
        "branch": branch_name,
        "ref": commit_sha
    })

    if create_response.status_code in [200, 201]:
        print("secureagent/fixes branch created")
        return True

    print(f"Failed to create fixes branch: {create_response.status_code}")
    return False


def commit_fix_to_branch(gitlab_project_id, finding, username: str, mr_iid: str) -> str:
    """
    Commits the generated fix as a uniquely named file on the secureagent/fixes branch.
    File naming includes developer username and MR ID to avoid conflicts between developers.
    Uses PUT to update if the file already exists, e.g. on re-scan of the same MR.
    Returns the committed file path, or None on failure.
    """
    headers = {"PRIVATE-TOKEN": GITLAB_TOKEN}
    vuln_slug = finding.vulnerability.lower().replace(" ", "-").replace("(", "").replace(")", "")
    file_path = f"fixes/fix-{username}-mr{mr_iid}-{vuln_slug}.py"
    encoded_path = file_path.replace("/", "%2F")
    commit_url = f"{GITLAB_BASE_URL}/projects/{gitlab_project_id}/repository/files/{encoded_path}"

    file_content = (
        f"# SecureAgent Fix\n"
        f"# Developer: {username}\n"
        f"# MR: #{mr_iid}\n"
        f"# Vulnerability: {finding.vulnerability}\n"
        f"# Severity: {finding.severity}\n\n"
        f"# Vulnerable code:\n"
        f"# {finding.vulnerable_code}\n\n"
        f"# Secure replacement:\n"
        f"{finding.fixed_code}\n"
    )

    commit_payload = {
        "branch": "secureagent/fixes",
        "content": file_content,
        "commit_message": f"[SecureAgent] Fix {finding.vulnerability} for {username} MR#{mr_iid}"
    }

    response = requests.post(commit_url, headers=headers, json=commit_payload)

    if response.status_code == 201:
        print(f"Fix committed to secureagent/fixes: {file_path}")
        return file_path

    if response.status_code == 400:
        # File already exists, update it with PUT
        commit_payload["commit_message"] = f"[SecureAgent] Update fix for {username} MR#{mr_iid}"
        put_response = requests.put(commit_url, headers=headers, json=commit_payload)
        if put_response.status_code == 200:
            print(f"Fix updated on secureagent/fixes: {file_path}")
            return file_path
        print(f"Failed to update fix: {put_response.status_code}, {put_response.text}")
        return None

    print(f"Failed to commit fix: {response.status_code}, {response.text}")
    return None


def create_merge_request(gitlab_project_id, finding, branch: str, mr_iid: str, username: str, issue_url: str) -> str:
    """
    Opens a Merge Request from secureagent/fixes to the developer's source branch.
    Developer username in the title makes it easy to search and filter by name.
    Reuses existing open MR if one already exists for the fixes branch.
    Returns the MR URL.
    """
    headers = {"PRIVATE-TOKEN": GITLAB_TOKEN}

    # Prevent infinite loop, don't create MR when source is already secureagent/fixes
    if branch == "secureagent/fixes":
        print("Source branch is secureagent/fixes, skipping MR creation")
        return None

    if not ensure_fixes_branch(gitlab_project_id, branch):
        print("Could not ensure fixes branch exists")
        return None

    file_path = commit_fix_to_branch(gitlab_project_id, finding, username, mr_iid)
    if not file_path:
        print("Could not commit fix to branch")
        return None

    mr_body = (
        f"## SecureAgent, Automated Security Fix\n\n"
        f"**Developer:** {username}\n"
        f"**Vulnerability:** {finding.vulnerability}\n"
        f"**Severity:** {finding.severity}\n\n"
        f"**Related Issue:** {issue_url}\n\n"
        f"### Fix Applied\n"
        f"```\n{finding.fixed_code}\n```\n\n"
        f"### Why This Fix Works\n"
        f"{finding.why_fix_works}\n\n"
        f"### Developer Lesson\n"
        f"{finding.developer_lesson}\n\n"
        f"*Please review and apply the fix to your code before merging.*"
    )

    mr_response = requests.post(
        f"{GITLAB_BASE_URL}/projects/{gitlab_project_id}/merge_requests",
        headers=headers,
        json={
            "source_branch": "secureagent/fixes",
            "target_branch": branch,
            "title": f"[SecureAgent] {username}, {finding.severity} {finding.vulnerability} Fix (MR #{mr_iid})",
            "description": mr_body,
            "labels": "security,secureagent"
        }
    )

    if mr_response.status_code == 201:
        mr_url = mr_response.json().get("web_url")
        print(f"Merge Request created: {mr_url}")
        return mr_url

    if mr_response.status_code == 409:
        # MR already exists for secureagent/fixes, find and return the existing one
        existing_response = requests.get(
            f"{GITLAB_BASE_URL}/projects/{gitlab_project_id}/merge_requests?source_branch=secureagent/fixes&state=opened",
            headers=headers
        )
        if existing_response.status_code == 200 and existing_response.json():
            existing_mr_url = existing_response.json()[0].get("web_url")
            print(f"Existing MR found: {existing_mr_url}")
            return existing_mr_url
        return None

    print(f"Failed to create MR: {mr_response.status_code}, {mr_response.text}")
    return None


def post_final_report(gitlab_project_id, mr_iid, finding, before_proof: dict, after_proof: dict, attempts: int, issue_url: str, fix_mr_url: str) -> None:
    """
    Posts the final security report as a comment on the original developer MR.
    Includes validation summary table, attack proof table, fix code, and links.
    This is what the developer sees when the full pipeline completes.
    """
    headers = {"PRIVATE-TOKEN": GITLAB_TOKEN}

    validation_table = (
        "| Validation Step | Status | Notes |\n"
        "|---|---|---|\n"
        f"| Gemini Code Analysis | :white_check_mark: Passed | {finding.vulnerability} detected at line {finding.line_number} |\n"
        f"| Fix Validation | :white_check_mark: Passed | Secure patterns verified, no dangerous patterns detected |\n"
        f"| Sandbox Deployment | :white_check_mark: Passed | Ephemeral Cloud Run instance deployed |\n"
        f"| Live Attack Proof | :white_check_mark: Passed | HTTP {before_proof['status_code']}, attack succeeded before fix |\n"
        f"| Fix Verification | :white_check_mark: Passed | HTTP {after_proof['status_code']}, attack blocked after fix (attempt {attempts}) |\n"
        f"| Human Review | :hourglass: Pending | Awaiting developer review |\n"
    )

    proof_table = (
        "| | Before Fix | After Fix |\n"
        "|---|---|---|\n"
        f"| **Payload** | `{before_proof['payload_used']}` | `{after_proof['payload_used']}` |\n"
        f"| **Target Field** | `{before_proof['field_targeted']}` | `{after_proof['field_targeted']}` |\n"
        f"| **HTTP Status** | {before_proof['status_code']} | {after_proof['status_code']} |\n"
        f"| **Response** | {before_proof['response_body'][:50]} | {after_proof['response_body'][:50]} |\n"
        f"| **Result** | :red_circle: Attack succeeded | :green_circle: Attack blocked |\n"
    )

    vulnerable_code_block = "```\n" + finding.vulnerable_code + "\n```"
    fixed_code_block = "```\n" + finding.fixed_code + "\n```"

    report = (
        "## :red_circle: SecureAgent Security Report\n\n"
        f"**Vulnerability:** {finding.vulnerability}\n"
        f"**Severity:** {finding.severity}\n"
        f"**OWASP Category:** {finding.owasp_category}\n\n"
        "---\n\n"
        "## Validation Summary\n"
        f"{validation_table}\n\n"
        "## Attack Proof\n"
        f"{proof_table}\n\n"
        "---\n\n"
        "## Vulnerable Code\n"
        f"{vulnerable_code_block}\n\n"
        f"**Why it's vulnerable:** {finding.why_vulnerable}\n\n"
        "## Recommended Fix\n"
        f"{fixed_code_block}\n\n"
        f"**Why it works:** {finding.why_fix_works}\n\n"
        "## Developer Lesson\n"
        f"{finding.developer_lesson}\n\n"
        "---\n\n"
        f":spiral_notepad: **Full Report:** {issue_url}\n"
        f":wrench: **Fix MR:** {fix_mr_url}\n\n"
        "*SecureAgent, Don't just find vulnerabilities, understand them, prove them, fix them.*"
    )

    url = f"{GITLAB_BASE_URL}/projects/{gitlab_project_id}/merge_requests/{mr_iid}/notes"
    response = requests.post(url, headers=headers, json={"body": report})

    if response.status_code == 201:
        print(f"Final report posted to MR #{mr_iid}")
    else:
        print(f"Failed to post final report: {response.status_code}")